import Link from "next/link";
import "./globals.css";
import axios from "axios";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getTopics() {
  try {
    const { data } = await axios.get("http://localhost:9999/topics", {
      headers: { "Content-Type": "application/json" },
    });
    return data;
  } catch (err) {
    console.error(err);
    return [];
  }
}

export default async function RootLayout({ children }) {
  const topics = await getTopics();

  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">WEB</Link>{" "}
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              {" "}
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
          <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="Delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
